///////// Usuarios /////////

### Buscar todos os usuários
GET http://localhost:3000/api/usuarios

### Buscar usuário por ID
GET http://localhost:3000/api/usuarios/1

### Criar novo usuário
POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
  "nome": "Ariel Mouadebs",
  "email": "amouadeb20067@gmail.com",
  "senha": "segredo123"
}

### Atualizar usuário
PUT http://localhost:3000/api/usuarios/1
Content-Type: application/json

{
  "nome": "Ariel Atualizado",
  "email": "ariel24@gmail.com",
  "senha": "segredo456"
}

### Deletar usuário
DELETE http://localhost:3000/api/usuarios/1



///////// Eventos /////////

### Buscar todos os eventos
GET http://localhost:3000/api/eventos

### Buscar evento por ID
GET http://localhost:3000/api/eventos/1

### Criar novo evento
POST http://localhost:3000/api/eventos
Content-Type: application/json

{
  "titulo": "Jogo do Palmeiras",
  "descricao": "Venha assistir o jogo do Palmeiras, em sua ultima partida antes do mundial de clubes",
  "local": "Rua Turiassu 1840",
  "data": "2025-06-03",
  "status": "Aguardando"
}

### Atualizar evento
PUT http://localhost:3000/api/eventos/1
Content-Type: application/json

{
  "titulo": "Jogo do Palmeiras - Atualizado",
  "descricao": "Jogo decisivo!",
  "local": "Rua Palestra Itália 1000",
  "data": "2025-06-04",
  "status": "Confirmado"
}

### Deletar evento
DELETE http://localhost:3000/api/eventos/1



///////// Inscrições /////////

### Buscar todas as inscrições
GET http://localhost:3000/api/inscricoes

### Buscar inscrição por ID
GET http://localhost:3000/api/inscricoes/1

### Criar nova inscrição
POST http://localhost:3000/api/inscricoes
Content-Type: application/json

{
  "usuario_id": 1,
  "evento_id": 2
}

### Atualizar inscrição
PUT http://localhost:3000/api/inscricoes/1
Content-Type: application/json

{
  "usuario_id": 1,
  "evento_id": 3
}

### Deletar inscrição
DELETE http://localhost:3000/api/inscricoes/1
