///////// Usuarios /////////



### Buscar todas as categorias
GET http://localhost:3000/api/usuarios

{ "nome": "Maria Silva",
  "email": "maria@exemplo.com",
  "senha": "senha123"}

### Buscar categoria por ID
GET http://localhost:3000/api/usuarios/:id

{

}

### Criar nova categoria
POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
 
}

### Atualizar categoria
PUT http://localhost:3000/api/usuarios/:id

Content-Type: application/json

{
  
}

### Deletar categoria
DELETE http://localhost:3000/api/usuarios/:id



///////// Eventos /////////


### Buscar todas as categorias
GET http://localhost:3000/api/eventos

### Buscar categoria por ID
GET http://localhost:3000/api/eventos/:id

### Criar nova categoria
POST http://localhost:3000/api/eventos
Content-Type: application/json

{
  "titulo": "Ariel",
  "descricao": "Foda",
  "local" : "Rua 1",
  "data" : "2023-10-10",
  "status" : "Pendente"
}

### Atualizar categoria
PUT http://localhost:3000/api/eventos/:id

Content-Type: application/json

{
  "titulo": "Ariel",
  "descricao": "Foda",
  "local" : "Rua 1",
  "data" : "2023-10-10",
  "status" : "Pendente"
}

### Deletar categoria
DELETE http://localhost:3000/api/eventos/:id



///////// Inscirção /////////


### Buscar todas as categorias
GET http://localhost:3000/api/inscricoes

{ "usuario_id": 1,
  "evento_id": 2 }

### Buscar categoria por ID
GET http://localhost:3000/api/inscricoes/:id

{

}

### Criar nova categoria
POST http://localhost:3000/api/inscricoes
Content-Type: application/json

{
 
}

### Atualizar categoria
PUT http://localhost:3000/api/inscricoes/:id

Content-Type: application/json

{
  
}

### Deletar categoria
DELETE http://localhost:3000/api/inscircoes/:id
