### Buscar todas as categorias
GET http://localhost:3000/api/eventos

### Buscar categoria por ID
GET http://localhost:3000/api/eventos/:id

### Criar nova categoria
POST http://localhost:3000/api/eventos
Content-Type: application/json

{
  "nome": "Ariel",
  "descricao": "Foda"
}

### Atualizar categoria
PUT http://localhost:3000/api/eventos/:id
Content-Type: application/json

{
  "nome": "Ariel",
  "descricao": "Foda"
}

### Deletar categoria
DELETE http://localhost:3000/api/eventos/:id